#+DEVLOG

* Sun Jan 11

At this point I want to create a table to hold each post to roll out features like filtering display by post date.

Schema:

#+begin_src
CREATE TABLE IF NOT EXISTS "entries" (
	"feed_id"	INTEGER NOT NULL,
	"published_date"	INTEGER NOT NULL,
	"is_read"	INTEGER NOT NULL DEFAULT 0,
	"guid"	TEXT NOT NULL UNIQUE,
	"title"	TEXT NOT NULL,
	"url"	TEXT NOT NULL,
	PRIMARY KEY("feed_id","guid"),
	FOREIGN KEY("feed_id") REFERENCES "feeds"("id") ON DELETE CASCADE
);
#+end_src


Note that on every database "migration" I have to run:

: scp db/hrmss.sqlite nyoki@mojave:/var/lib/dokku/data/storage/hrmss/db/   

Having done this, I now make sure posts on the home page are populated from the database and not from the XML. This means that I will have to implement a separate "fetch" or "refresh" function.

I wonder... can I do feed->entries to see what's in it? Let's try in sqlite3.

I cannot. The databases enforces rules, not relationships.

I have updated the feeds db schema to set the last_fetched_at column to the current time stamp when creating a new feed. Will have to migrate db.

I'll take a break. It's 10:10pm.

I'm thinking to sort by date I could do

index.php?filter="2w";


* Mon 12 Jan

I've added a refresh script to update feeds with a hard cache of 1 hour. I created a cron job in the VPS to run at the top of the hour and refresh the feeds. There is now also a hrmss-refresh.log file.

: $ sudo touch /var/log/hrmss-refresh.log
: $ sudo chown dokku:dokku /var/log/hrmss-refresh.log


None of the above was necesary. To set a cron job first you create an app.json file and specify the cron task. It can be run easily manually too.

https://dokku.com/docs/processes/scheduled-cron-tasks/

: $ dokku cron:list hrmss

Which outputs:

#+begin_src
ID                                                          Schedule  Command
10iwvlckpbhiq09zcaztgpflusojzwi1tzvyzpd2xf8pdzjojdwbzawcc9  @hourly   php bin/refresh.php
#+end_src

: $ dokku cron:run hrmss 10iwvlckpbhiq09zcaztgpflusojzwi1tzvyzpd2xf8pdzjojdwbzawcc9

When I went on today's walk I checked the feed and noticed some articles from "today" were missing. This is due to the difference in timezone from the production server (UTC) and my local environment.

At first I thought my queries were wrong, so I added a couple of missing spaces and even the 'localtime' parameter to the index file (#[[https://github.com/pabloenoc/hermes/commit/494e328694d2ab52a5b2fb130fdb38390e2f35d6][494e328]]).

It's still not working with localtime. I'll set the timezone with dokku manually.

: $ dokku config:set hrmss TZ=America/Los_Angeles

This restarted the app. 

* Tue Jan 13

I notice that adding new feeds does not automatically update the db with its entries. Nevermind. It's just there were no posts for the default of today... it's 1:16am and I'm tired. 

Tonight the goal is to refactor the project's file structure. There's a few scattered files that would be better off within their own directory. Have not yet decided whether I'll be using composer... but the dokku deployment makes it all but obligatory. I want to move to something like this:

#+begin_src
┌────────────────────────┐
│ app.json               │ ← process scheduling (Dokku/Heroku)
├────────────────────────┤
│ Procfile               │ ← runtime entrypoints
├────────────────────────┤
│ bin/*.php              │ ← CLI scripts
├────────────────────────┤
│ vendor/autoload.php    │ ← Composer boundary
├────────────────────────┤
│ src/                   │ ← application logic
├────────────────────────┤
│ templates/             │ ← presentation
├────────────────────────┤
│ public/index.php       │ ← web entrypoint
└────────────────────────┘
#+end_src

Still not sure where to start. Probably the database.

Either way, methodology involves:

creating a whole new directory titled CLEANUP-hrmss

Slowly bring over the functionality until it's clean. 

What is settings.php doing?

- opening db
- running a query from FEEDS

feeds.php
- CREATE feeds
- DELETE feed

I think I'll move some stuff away from settings.php by going to feeds.php from the form. Starting with create action. 


* Wed Jan 14

Today the dissasociated blog showed up on NetNewsWire but not on Hermes. So today the focus is on dates.

There's a chance it's because the article came out at 12:00pm and I saw it only at 12:48. I deleted and added the feed again but this was after 1:00pm. Bad testing. For peace of mind I'd like to see the hour anyway.

I suppose what keeps me coming back to a no-framework PHP development experience is the speed with which I can implement new ideas. It also puts me behind the desk of the software architect, leading me to make good design choices or deal with the consequences.

* Thu Jan 15

It's about time I begin refactoring the project. I have a couple of hours before I start work so I'll begin with simple stuff to get the ball rolling.

The difference between include and require is that require will stop execution if there is an error. Let's explore with that.

What if the View and the Controller went together?

That's real progress. I created new_feed.php and delete_feed.php, each of the files interacts with the database (bridging model and controller) and it also displays its respective form (view). Keeps things cleaner. 

* Fri Jan 16

I've been thinking about how to implement the "read article" feature. Some posts are short enough that I can read them entirely from my phone, so it seems useless to keep them hanging on the home page all day. It's a race to the smiley face. 

* Wed Jan 21

I also haven't addressed **users**. It's nice and all to have a regular app that only I can use, but what of users? Would it not be nice to have multiple users?

Is that where I should start when I'm working on a large project? Perhaps that would be better...

At 10:05PM I've added a rudimentary login.php script that sets a session ID. No checking if cookies allowed or similar. Database migrations remain a pain. Indeed, I have to use the following command to copy my database.

I'm also now requiring authentication to access home page and settings. This makes things cleaner. I can slowly roll out everything else. 
